### PR TITLE
tweak the Makefile for better distro support

### PR DESCRIPTION
**Pull request by cuviper**
These commits are designed to improve support for distro packaging, for Fedora in particular.

### CODE REVIEW

**Comment by jmendeth** [comment]
Looks good to me! @devinus?

**Comment by cuviper** [comment]
Any further opinion?

**Comment by devinus** [comment]
I think it looks good.

**Comment by cuviper** [comment]
Thanks for merging!

**Comment by jmendeth** [comment]
Okay, I'll release a patch version with what we have now.

**Pull request merged**
